# M1-INF4 – Python Workshop for Data Analysis
## Session 1 – Python & NumPy Essentials

**Master 1 IBI / SBI — Paris 1 Panthéon-Sorbonne**

---

## Rendu du groupe

**Membres :**
- Ryles AIT-MOHAMMED
- Aliou DIALLO
- Meryem BERRAMOU
- Rita HDIDOU

### Notre approche
Pour ce notebook, nous avons privilégié un code **simple, lisible et vérifiable** : noms de variables explicites, résultats affichés clairement et utilisation des outils adaptés à chaque étape (Python standard, NumPy puis pandas).

Notre objectif n'était pas seulement d'obtenir les bons résultats, mais aussi de pouvoir **expliquer la logique de chaque traitement** et de garder un notebook facile à relire par l'ensemble du groupe.

### Learning objectives

By the end of this session, students will be able to:

- Use a Jupyter Notebook in VS Code
- Refresh essential Python programming concepts for data analysis
- Reuse simple Python functions in a short business problem
- Manipulate numerical data with NumPy
- Use indexing, slicing, and vectorized operations
- Compute basic descriptive statistics
- Load and inspect a real dataset with pandas

### Today's workflow

Python refresher → NumPy (main new content) → Real-world data

## 1. Getting started with Jupyter Notebooks

A Jupyter Notebook combines:

- **Markdown cells** for explanations and documentation
- **Code cells** for executable Python code
- **Outputs** displayed directly below the code

Throughout this course, we will use notebooks to explore, manipulate, visualize, and interpret data.

In [1]:
print("Welcome to M1-INF4!")
print("Python is ready.")

Welcome to M1-INF4!
Python is ready.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("NumPy version:", np.__version__)
print("pandas version:", pd.__version__)
print("Environment ready!")

NumPy version: 2.5.3
pandas version: 3.0.6
Environment ready!

## 2. Python Refresher for Data Analysis

Before working with data, let's review a few Python concepts that we will use throughout the course:

- variables and basic data types
- lists and dictionaries
- indexing and slicing
- conditions and loops
- functions

This section is a quick refresher rather than a complete introduction to Python.
You have already studied algorithmic concepts and object-oriented programming; Python syntax may be less familiar. We will not study programming from scratch. Read familiar examples independently; use the explanations when needed.

Additional Python exercises and their solutions are available in **Appendix A (extra practice)**.

In [3]:
# Basic Python objects

course = "Data Analysis with Python"
students = 28
duration = 3
is_master_course = True

print(course)
print(type(course))
print(type(students))
print(type(duration))
print(type(is_master_course))

Data Analysis with Python
<class 'str'>
<class 'int'>
<class 'int'>
<class 'bool'>

### 2.1 Lists and indexing

A Python list stores an ordered collection of values.

Python uses **zero-based indexing**: the first element has index `0`.

In [4]:
scores = [12, 15, 9, 18, 14]

print("All scores:", scores)
print("First score:", scores[0])
print("Last score:", scores[-1])
print("First three scores:", scores[:3])

All scores: [12, 15, 9, 18, 14]
First score: 12
Last score: 14
First three scores: [12, 15, 9]

### 2.2 Dictionaries

A Python dictionary stores data as **key-value pairs**.

Dictionaries are useful when data have meaningful labels rather than numerical positions.

In [5]:
student = {
    "name": "Alice",
    "program": "SBI",
    "grade": 15.5,
    "passed": True
}

print(student)
print("Name:", student["name"])
print("Grade:", student["grade"])

{'name': 'Alice', 'program': 'SBI', 'grade': 15.5, 'passed': True}
Name: Alice
Grade: 15.5

In [6]:
student["grade"] = 16
student["year"] = "M1"

print(student)

{'name': 'Alice', 'program': 'SBI', 'grade': 16, 'passed': True, 'year': 'M1'}

### 2.3 Conditions and loops

Conditions allow a program to make decisions.

Loops allow us to repeat an operation over several values.

In [7]:
scores = [12, 15, 9, 18, 14]

for score in scores:
    if score >= 10:
        print(score, "→ Pass")
    else:
        print(score, "→ Fail")

12 → Pass
15 → Pass
9 → Fail
18 → Pass
14 → Pass

### 2.4 Functions

A function groups reusable instructions.

Functions help us avoid repeating code and make data-processing workflows easier to understand.

In [8]:
def classify_score(score):
    if score >= 10:
        return "Pass"
    else:
        return "Fail"


print(classify_score(15))
print(classify_score(8))

Pass
Fail

### ✏️ Mini-challenge — A first sales report

You are a junior data analyst for an e-commerce company. Your manager gives you the sales amounts (in euros) for six completed orders. Prepare a short report using **plain Python**, before moving to NumPy.

**Work in pairs:** agree on an approach, write your code, then compare and explain your results. Use the refresher examples if needed.

1. Display the number of orders, total sales and average sales per order.
2. Write `classify_sales(value)`: return `"High"` for a value greater than or equal to 150, and `"Standard"` otherwise. Apply it to each amount.
3. Use a loop and a condition to build a list of the amounts classified as `"High"`.
4. Store the number of orders, total and mean in a dictionary called `report`, using the keys `"orders"`, `"total"`, `"mean"`. Print it and explain one result to your partner.

**Self-check:** 6 orders; total €770; average approximately €128.33; high amounts `[180, 160]`. Interpret the average as sales per completed order, not monthly sales or sales per customer.

Do not open the solution until you have tried. The purpose is to diagnose Python fluency, not introduce new syntax.

In [9]:
sales = [120, 95, 140, 180, 75, 160]

# 1. Number of orders, total and mean
number_of_orders = len(sales)
total_sales = sum(sales)
mean_sales = total_sales / number_of_orders

print("Nombre de commandes :", number_of_orders)
print("Total :", total_sales)
print("Moyenne :", mean_sales)


# 2. Define classify_sales(value), then apply it to each amount
def classify_sales(value):
    if value >= 150:
        return "High"
    else:
        return "Standard"

for value in sales:
    print(value, "→", classify_sales(value))

# 3. Build the list of high amounts using a loop and a condition
high_sales = []

for value in sales:
    if value >= 150:
        high_sales.append(value)

print("Ventes High :", high_sales)

# 4. Build and display report
report = {
    "orders": number_of_orders,
    "total": total_sales,
    "mean": mean_sales
}

print("Report :", report)

**Pourquoi cette solution ?**  
Nous avons commencé par `len()` et `sum()` car ce sont les outils Python les plus directs pour compter les commandes et calculer le total. La moyenne est ensuite obtenue à partir de ces deux résultats. Pour les ventes élevées, une boucle avec une condition rend la logique très lisible, puis le dictionnaire `report` regroupe les indicateurs principaux dans une structure claire.

<details>
<summary>Solution — open after attempting the challenge</summary>

```python
sales = [120, 95, 140, 180, 75, 160]
number_of_orders = len(sales)
total_sales = sum(sales)
mean_sales = total_sales / number_of_orders
print(number_of_orders, total_sales, mean_sales)

def classify_sales(value):
    if value >= 150:
        return "High"
    else:
        return "Standard"

high_sales = []
for value in sales:
    print(value, "→", classify_sales(value))
    if value >= 150:
        high_sales.append(value)

report = {"orders": number_of_orders, "total": total_sales, "mean": mean_sales}
print(high_sales)
print(report)
```

The average describes these six orders; it does not explain why their values differ. The list is non-empty, so division by the number of orders is valid here.

</details>

## 3. From Python Lists to NumPy Arrays

Python lists are convenient, but data analysis often requires performing numerical operations on many values.

**NumPy** (Numerical Python) provides efficient multidimensional arrays and numerical operations.

Let's compare a Python list with a NumPy array.
**Main new content:** NumPy arrays, indexing, filtering, vectorization and descriptive statistics.

The sales examples describe small fictional business datasets. Their values and observation units are stated separately; they are not all the same dataset.

In [10]:
import numpy as np

sales_list = [120, 135, 150, 165]

sales_array = np.array(sales_list)

print("Python list:", sales_list)
print("NumPy array:", sales_array)

Python list: [120, 135, 150, 165]
NumPy array: [120 135 150 165]

In [11]:
# What happens if we multiply by 2?

print("Python list:")
print(sales_list * 2)

print("\nNumPy array:")
print(sales_array * 2)

Python list:
[120, 135, 150, 165, 120, 135, 150, 165]

NumPy array:
[240 270 300 330]

### 3.1 Exploring NumPy arrays

A NumPy array has several useful properties:

- `shape` — dimensions of the array
- `size` — total number of elements
- `dtype` — data type of the elements
- `ndim` — number of dimensions

In [12]:
sales = np.array([120, 135, 128, 150, 165, 172])

print("Array:", sales)
print("Shape:", sales.shape)
print("Size:", sales.size)
print("Data type:", sales.dtype)
print("Number of dimensions:", sales.ndim)

Array: [120 135 128 150 165 172]
Shape: (6,)
Size: 6
Data type: int64
Number of dimensions: 1

### 3.2 Indexing and slicing

NumPy arrays use the same basic indexing principles as Python lists.

We can access individual observations or select subsets of an array.

In [13]:
sales = np.array([120, 135, 128, 150, 165, 172])

print("First value:", sales[0])
print("Last value:", sales[-1])
print("First three values:", sales[:3])
print("Values from index 2 to 4:", sales[2:5])

First value: 120
Last value: 172
First three values: [120 135 128]
Values from index 2 to 4: [128 150 165]

### 3.3 Filtering data

NumPy can select observations that satisfy a condition.

The expression below creates a Boolean array containing `True` or `False` for each observation.

In [14]:
sales >= 150

array([False, False, False,  True,  True,  True])

In [15]:
# Use the Boolean mask to select the matching observations
print("Sales >= 150:", sales[sales >= 150])

Sales >= 150: [150 165 172]

### 3.4 Vectorized operations

NumPy allows us to perform an operation on an entire array without writing an explicit loop.

This is called **vectorization**.

In [16]:
sales = np.array([120, 135, 128, 150, 165, 172])

# Apply a 10% increase
sales_after_increase = sales * 1.10

print("Original sales:", sales)
print("After 10% increase:", sales_after_increase)

Original sales: [120 135 128 150 165 172]
After 10% increase: [132.  148.5 140.8 165.  181.5 189.2]

In [17]:
difference = sales_after_increase - sales

print("Increase:", difference)

Increase: [12.  13.5 12.8 15.  16.5 17.2]

### 3.5 Descriptive statistics

NumPy provides functions for computing common summary statistics.

These statistics help us obtain a first understanding of a dataset.

In [18]:
sales = np.array([120, 135, 128, 150, 165, 172])

print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Standard deviation:", np.std(sales))

Mean: 145.0
Median: 142.5
Minimum: 120
Maximum: 172
Standard deviation: 19.008769905844336

**“Why might the median sometimes be more informative than the mean?”**

**Notre réponse :** la médiane peut être plus représentative lorsque les données contiennent des valeurs extrêmes, car elle est beaucoup moins influencée par ces valeurs que la moyenne.

### ✏️ Your turn — Monthly revenue analysis

A company recorded the following monthly revenues (in thousands of euros):

```python
revenue = np.array([42, 48, 51, 39, 55, 62, 58, 70, 65, 74, 69, 80])
```

Try the six tasks before opening the solution.

1. Display the number of observations.
2. Compute the mean revenue.
3. Find the minimum and maximum revenue.
4. Select all months with revenue greater than or equal to 60.
5. Apply a hypothetical 5% increase to all revenues.
6. Count how many months have revenue greater than or equal to 60.

In [21]:

revenue = np.array([42, 48, 51, 39, 55, 62, 58, 70, 65, 74, 69, 80])

# Your code here
import numpy as np

revenue = np.array([42, 48, 51, 39, 55, 62, 58, 70, 65, 74, 69, 80])

# 1. Nombre d'observations
print("Nombre d'observations :", revenue.size)

# 2. Moyenne
print("Moyenne :", np.mean(revenue))

# 3. Minimum et maximum
print("Minimum :", np.min(revenue))
print("Maximum :", np.max(revenue))

# 4. Revenus >= 60
high_revenue = revenue[revenue >= 60]
print("Revenus >= 60 :", high_revenue)

# 5. Augmentation de 5 %
revenue_after_increase = revenue * 1.05
print("Après augmentation de 5 % :", revenue_after_increase)

# 6. Nombre de mois avec un revenu >= 60
number_high_months = np.sum(revenue >= 60)
print("Nombre de mois >= 60 :", number_high_months)

**Pourquoi cette solution ?**  
Ici, nous utilisons NumPy pour éviter des boucles inutiles : les fonctions `mean`, `min` et `max` calculent directement les statistiques, le masque `revenue >= 60` filtre les valeurs concernées et la multiplication par `1.05` applique l'augmentation à tout le tableau en une seule opération. `np.sum(revenue >= 60)` permet ensuite de compter simplement le nombre de mois répondant au critère.

In [22]:
# Solution

print("Number of observations:", revenue.size)
print("Mean:", np.mean(revenue))
print("Minimum:", np.min(revenue))
print("Maximum:", np.max(revenue))

high_revenue = revenue[revenue >= 60]
print("Revenue >= 60:", high_revenue)

revenue_after_increase = revenue * 1.05
print("After 5% increase:", revenue_after_increase)

print("Number of months >= 60:", np.sum(revenue >= 60))

Number of observations: 12
Mean: 59.416666666666664
Minimum: 39
Maximum: 80
Revenue >= 60: [62 70 65 74 69 80]
After 5% increase: [44.1  50.4  53.55 40.95 57.75 65.1  60.9  73.5  68.25 77.7  72.45 84.  ]
Number of months >= 60: 6

### 3.6 Two-dimensional arrays — OPTIONAL / IF TIME ALLOWS

NumPy can also represent data in multiple dimensions.

A two-dimensional array can be viewed as a table composed of rows and columns.
This optional subsection is not a prerequisite for the pandas introduction. You can continue directly to section 4.

In [25]:
data = np.array([
    [120, 10],
    [135, 12],
    [150, 15],
    [165, 14]
])

print(data)
print("Shape:", data.shape)

[[120  10]
 [135  12]
 [150  15]
 [165  14]]
Shape: (4, 2)

In [26]:
# First row
print(data[0])

# First column
print(data[:, 0])

# Second column
print(data[:, 1])

[120  10]
[120 135 150 165]
[10 12 15 14]

## 4. From NumPy to pandas: Working with Real Data

So far, we have manipulated data stored in Python lists and NumPy arrays.

In real data-analysis projects, data are often stored in tabular files such as CSV files.

The **pandas** library provides the `DataFrame`, a convenient structure for working with rows and columns.

Let's explore our first real dataset.
Use `homelessness.csv` for the guided exploration. The second CSV exercise provides optional further practice.

Keep this notebook in the course `notebooks/` directory. The relative paths require a working directory of `notebooks/` and the course CSV files in `../data/`. The real CSV files are not embedded in this notebook.

In [47]:
import pandas as pd

homelessness = pd.read_csv("../data/homelessness.csv")

### 4.1 First look at the dataset

Before analyzing a new dataset, we should first understand its structure.

Some useful questions are:

- What does the dataset look like?
- How many rows and columns are there?
- What are the column names?
- What types of data do the columns contain?

In [28]:
homelessness.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

**What do you think one row represents? What variables can you identify?**

**Notre observation :** une ligne représente ici un État américain. Les principales variables sont la région, l'État, le nombre de personnes sans domicile vivant seules (`individuals`), le nombre de membres de familles sans domicile (`family_members`) et la population de l'État (`state_pop`).

In [29]:
homelessness.shape

(51, 6)

In [31]:
homelessness.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='str')

In [30]:
homelessness.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     str
 2   state           51 non-null     str
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), str(2)
memory usage: 2.5 KB

### 💡 Takeaway

When opening a new dataset, a useful first workflow is:

```python
df.head()
df.shape
df.columns
df.info()

```

These commands help us understand the content, dimensions, variables, and data types before performing any analysis.

### ✏️ Your turn — Explore a second dataset (OPTIONAL / FOLLOW-UP)

Now explore the `sales_subset.csv` dataset.

1. Load the dataset using `pd.read_csv()`.
2. Display its first rows.
3. Determine its number of rows and columns.
4. Display the column names.
5. Inspect its data types using `info()`.

**Question:** Which columns seem numerical? Which columns seem categorical?
Use the same exploration workflow on this second dataset to consolidate your understanding.

In [32]:
# Load the dataset
sales = pd.read_csv("../data/sales_subset.csv")

# Explore the dataset
print(sales.head())
print(sales.shape)
print(sales.columns)
sales.info()

**Pourquoi cette solution ?**  
Avant d'analyser un dataset, nous vérifions d'abord sa structure. `head()` permet de voir les premières lignes, `shape` donne ses dimensions, `columns` liste les variables et `info()` permet de contrôler les types de données. Nous avons utilisé `print()` pour rendre les différents résultats visibles dans une seule cellule.

In [33]:
# Solution

sales = pd.read_csv("../data/sales_subset.csv")

print(sales.head())
print(sales.shape)
print(sales.columns)
sales.info()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [36]:
sales.shape

(10774, 10)

In [35]:
sales.columns

Index(['Unnamed: 0', 'store', 'type', 'department', 'date', 'weekly_sales',
       'is_holiday', 'temperature_c', 'fuel_price_usd_per_l', 'unemployment'],
      dtype='str')

In [34]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            10774 non-null  int64
 1   store                 10774 non-null  int64
 2   type                  10774 non-null  str
 3   department            10774 non-null  int64
 4   date                  10774 non-null  str
 5   weekly_sales          10774 non-null  float64
 6   is_holiday            10774 non-null  bool
 7   temperature_c         10774 non-null  float64
 8   fuel_price_usd_per_l  10774 non-null  float64
 9   unemployment          10774 non-null  float64
dtypes: bool(1), float64(4), int64(3), str(2)
memory usage: 768.2 KB

## 5. Session 1 — Key Takeaways

Today we moved from a Python refresher to real-world data analysis.

We reviewed:

- Python variables and data structures
- Lists, dictionaries, conditions, loops, and functions
- NumPy arrays
- Indexing and filtering
- Vectorized numerical operations
- Basic descriptive statistics
- Loading a CSV file with pandas
- First steps for exploring a DataFrame

### Next session

In the next session, we will focus on **data manipulation with pandas**:

**select → filter → sort → transform → aggregate**
**Check your understanding:** explain how list multiplication differs from array multiplication, distinguish a Boolean mask from the selected values, and name the first commands you would use to inspect a CSV.

### Vérification de compréhension

1. Une **liste Python multipliée par 2** est répétée deux fois, alors qu'un **tableau NumPy multiplié par 2** multiplie chaque valeur par 2.
2. Un **masque booléen** contient des `True` et `False` ; appliqué à un tableau NumPy, il permet de récupérer uniquement les valeurs correspondant aux `True`.
3. Pour une première inspection d'un CSV avec pandas, nous utilisons : `df.head()`, `df.shape`, `df.columns` et `df.info()`.

## Appendix A — Python exercises (extra practice)

Use these exercises and their solutions for additional practice or individual revision.

### ✏️ Your turn

Given the following list of monthly sales:

```python
sales = [120, 135, 128, 150, 165, 172]
```

1. Display the first value.
2. Display the last value.
3. Display the first three values.
4. Compute the number of observations using len().
5. Compute the total sales using sum().

In [43]:
sales = [120, 135, 128, 150, 165, 172]

print("First:", sales[0])
print("Last:", sales[-1])
print("First three:", sales[:3])
print("Number of observations:", len(sales))
print("Total:", sum(sales))

**Pourquoi cette solution ?**  
Cet exercice repose sur les opérations de base sur les listes : l'indice `0` récupère le premier élément, `-1` le dernier et `[:3]` les trois premiers. `len()` compte les observations tandis que `sum()` calcule directement leur total.

In [44]:
# Solution

print("First:", sales[0])
print("Last:", sales[-1])
print("First three:", sales[:3])
print("Number of observations:", len(sales))
print("Total:", sum(sales))

First: 120
Last: 172
First three: [120, 135, 128]
Number of observations: 6
Total: 870

### ✏️ Your turn

Consider the following sales data:

```python
sales = [120, 95, 140, 180, 75, 160]

```

Write a function called classify_sales() that:
- takes one sales value as input;
- returns "High" if the value is greater than or equal to 150;
- returns "Standard" otherwise.
Then apply the function to every value in sales.

In [45]:
sales = [120, 95, 140, 180, 75, 160]

def classify_sales(value):
    if value >= 150:
        return "High"
    else:
        return "Standard"

for value in sales:
    print(value, "→", classify_sales(value))

**Pourquoi cette solution ?**  
Nous avons isolé la règle de classification dans une fonction afin d'éviter de répéter le même test. La boucle applique ensuite cette fonction à chaque valeur de la liste, ce qui rend la solution réutilisable et facile à modifier si le seuil change.

In [46]:
# Solution

def classify_sales(value):
    if value >= 150:
        return "High"
    else:
        return "Standard"


for value in sales:
    print(value, "→", classify_sales(value))

120 → Standard
95 → Standard
140 → Standard
180 → High
75 → Standard
160 → High